### ISSUE TITLE
which versions supported?

### ISSUE THREAD

**Issue by pavellzubkov** [brcolow/pc-service-tool-pw-gen#1]
i try it for 4.92 version, but "Invalid password" in all configurations.

**Comment by brcolow** [comment]
Please give me a few days to investigate as I'm traveling. It should work with that version. Didn't know version 4 minor versions went up so high but the code should work for any 8 byte number (up to 255).

**Comment by brcolow** [comment]
Hi, I found some time for this. The issue was when calling the `generatePassword` method with values fed in from the UI (the HTML text fields) the expiration date in years was being treated as a string. I have now forced it to be treated as a number.

Please give the latest changes a try. Thanks!

**Comment by pavellzubkov** [comment]
thank you! now it worked on  this version on [mega](https://mega.nz/file/mt4SXKyK#VbrrVnEj3qaniKH_DG_ubGIF4m9WoPMl3OxrWKstSeI).
But. it work only if i set minor version 9. if i set 92 - not work. If i change brand to Yale it not worked again. by the way great script!)

**Comment by brcolow** [comment]
Okay that's good info - I will dig deeper into this in the next few days - and thanks!

**Comment by brcolow** [comment]
I can reproduce the error when the version is increases from 4.9 to 4.10 (and above).

Don't know why a second minor version digit causes problems as it is being decoded correctly. Although it seems that the version can be anything - even a different major version number - as long as it is less than 4.9.

It seems like I can fix the version issue by just truncating the minor version number to one digit.

I can also reproduce the error when switching from Hyster to Yale. Investigating this further...

**Comment by pavellzubkov** [comment]
ok. Service tool (4.92) have file "NMHG PC Service Tool.exe.config" in instalation folder witch contain row:
` <add key="AppBrand" value="Hyster"/>`
If I change value to Yale - then tool confirmed generated password with yale brand.( but get some errors about missing Yale logo files. And not matter minor version .. i tried 5,6,9 - all confirmed.
Thank you again)

**Comment by brcolow** [comment]
Nice find on the config file - I wasn't aware of that. I added a note to the README about that.

Now that we have truncated the minor version to one digit and added the note I believe both of these issues are addressed so I will close this. Thanks so much for testing the generator and your very helpful feedback/findings!
